// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConsStatus(arg1) {
  return window['go']['mysql']['Mysql']['GetConsStatus'](arg1);
}

export function GetConspercent(arg1) {
  return window['go']['mysql']['Mysql']['GetConspercent'](arg1);
}

export function GetMysqlLock(arg1) {
  return window['go']['mysql']['Mysql']['GetMysqlLock'](arg1);
}

export function GetMysqlProcesslist(arg1, arg2) {
  return window['go']['mysql']['Mysql']['GetMysqlProcesslist'](arg1, arg2);
}

export function KillMysqlProcesses(arg1, arg2) {
  return window['go']['mysql']['Mysql']['KillMysqlProcesses'](arg1, arg2);
}
