// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyseRdb(arg1) {
  return window['go']['redis']['Redis']['AnalyseRdb'](arg1);
}

export function GetPrefixkeys(arg1, arg2) {
  return window['go']['redis']['Redis']['GetPrefixkeys'](arg1, arg2);
}

export function GetRdbResultTitle() {
  return window['go']['redis']['Redis']['GetRdbResultTitle']();
}

export function GetRedisKeys(arg1, arg2) {
  return window['go']['redis']['Redis']['GetRedisKeys'](arg1, arg2);
}

export function GetRedisMemory(arg1) {
  return window['go']['redis']['Redis']['GetRedisMemory'](arg1);
}

export function GetRedisTop500Prefix(arg1) {
  return window['go']['redis']['Redis']['GetRedisTop500Prefix'](arg1);
}
