// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {redis} from '../models';

export function AnalyseRdb(arg1:string):Promise<string>;

export function GetPrefixkeys(arg1:string,arg2:string):Promise<Array<redis.RedisKey>>;

export function GetRdbResultTitle():Promise<Array<{[key: string]: string}>>;

export function GetRedisKeys(arg1:string,arg2:string):Promise<Array<redis.RedisKey>>;

export function GetRedisMemory(arg1:string):Promise<redis.RedisMomery>;

export function GetRedisTop500Prefix(arg1:string):Promise<Array<redis.RedisKey>>;
