// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {redis} from '../models';

export function AnalyseRdb(arg1:string):Promise<string>;

export function GetExpireMemoryPic(arg1:string):Promise<Array<any>>;

export function GetExpirePrefixs(arg1:string,arg2:string):Promise<Array<redis.RedisKey>>;

export function GetForverMemoryPic(arg1:string):Promise<Array<any>>;

export function GetPrefixDetail(arg1:string,arg2:string,arg3:string):Promise<Array<redis.RedisKey>>;

export function GetRdbResultTitle():Promise<Array<{[key: string]: string}>>;

export function GetRedisMemory(arg1:string):Promise<Array<{[key: string]: string}>>;
