// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCon(arg1) {
  return window['go']['main']['App']['AddCon'](arg1);
}

export function AnalyseRdb(arg1) {
  return window['go']['main']['App']['AnalyseRdb'](arg1);
}

export function DeleteCon(arg1) {
  return window['go']['main']['App']['DeleteCon'](arg1);
}

export function GetCons() {
  return window['go']['main']['App']['GetCons']();
}

export function GetConsStatus(arg1) {
  return window['go']['main']['App']['GetConsStatus'](arg1);
}

export function GetConspercent(arg1) {
  return window['go']['main']['App']['GetConspercent'](arg1);
}

export function GetFullCons() {
  return window['go']['main']['App']['GetFullCons']();
}

export function GetMysqlProcesslist(arg1, arg2) {
  return window['go']['main']['App']['GetMysqlProcesslist'](arg1, arg2);
}

export function GetPeople() {
  return window['go']['main']['App']['GetPeople']();
}

export function GetPrefixkeys(arg1, arg2) {
  return window['go']['main']['App']['GetPrefixkeys'](arg1, arg2);
}

export function GetRdbResultTitle() {
  return window['go']['main']['App']['GetRdbResultTitle']();
}

export function GetRedisKeys(arg1, arg2) {
  return window['go']['main']['App']['GetRedisKeys'](arg1, arg2);
}

export function GetRedisMemory(arg1) {
  return window['go']['main']['App']['GetRedisMemory'](arg1);
}

export function GetRedisTop500Prefix(arg1) {
  return window['go']['main']['App']['GetRedisTop500Prefix'](arg1);
}

export function KillMysqlProcesses(arg1, arg2) {
  return window['go']['main']['App']['KillMysqlProcesses'](arg1, arg2);
}

export function OpenDialog() {
  return window['go']['main']['App']['OpenDialog']();
}
