// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function AddCon(arg1:utils.Connection):Promise<string>;

export function DeleteCon(arg1:utils.Connection):Promise<string>;

export function GetFullCons():Promise<Array<utils.Connection>>;

export function GetWorkDir():Promise<string>;

export function OpenDialog():Promise<string>;

export function OpenDir():Promise<string>;

export function SetWorkDir(arg1:string):Promise<string>;
