// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function AddCon(arg1:utils.Connection):Promise<string>;

export function DeleteCon(arg1:utils.Connection):Promise<string>;

export function GetCons():Promise<Array<{[key: string]: string}>>;

export function GetFullCons():Promise<Array<utils.Connection>>;

export function OpenDialog():Promise<string>;
