// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCon(arg1) {
  return window['go']['main']['App']['AddCon'](arg1);
}

export function DeleteCon(arg1) {
  return window['go']['main']['App']['DeleteCon'](arg1);
}

export function GetCons() {
  return window['go']['main']['App']['GetCons']();
}

export function GetFullCons() {
  return window['go']['main']['App']['GetFullCons']();
}

export function OpenDialog() {
  return window['go']['main']['App']['OpenDialog']();
}
